services:
  - name: lego-investor
    type: web
    env: node
    buildCommand: apt-get update && apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget libgbm-dev && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Ceci indique qu'il faut définir cette variable manuellement
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    autoDeploy: true # Déploiement automatique lors des push sur la branche principale

  - type: static
    name: lego-investor-client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/client
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://lego-investor-api.onrender.com # Will be updated after API deployment 