services:
  - name: lego-investor
    type: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Ceci indique qu'il faut définir cette variable manuellement
    autoDeploy: true # Déploiement automatique lors des push sur la branche principale

  - type: static
    name: lego-investor-client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/client
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://lego-investor-api.onrender.com # Will be updated after API deployment 