services:
  - name: lego-investor-api
    type: web
    env: node
    buildCommand: |
      # Installation des dépendances pour Chrome
      apt-get update -y
      apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        wget \
        xdg-utils
      # Installation de Chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb
      # Installation des dépendances Node.js et build du serveur uniquement
      npm install
      npm run build:server
    startCommand: npm run start:api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Ceci indique qu'il faut définir cette variable manuellement
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    autoDeploy: true # Déploiement automatique lors des push sur la branche principale

  - type: static
    name: lego-investor-client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/client
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://lego-investor-api.onrender.com # Will be updated after API deployment 